# Generated by Django 4.2.7 on 2023-11-26 18:58

from django.db import migrations, models
import train_station.models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=train_station.models.train_image_file_path,
            ),
        ),
    ]
